name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *' # Every day at 10am UTC
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.branch_check.outputs.environment }}
    steps:
      - name: Choose Environment
        id: branch_check
        run: |
          echo "environment=${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    environment:
      name: "${{ needs.setup.outputs.target_env }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.19.1'
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Build the project
        env:
          BASE_URL: "${{ secrets.BASE_URL }}"
          GH_REPO: "${{ secrets.GH_REPO }}"
          MISSION_STATS_URL: "${{ secrets.MISSION_STATS_URL }}"
          PACKAGIST_STATS_URL: "${{ secrets.PACKAGIST_STATS_URL }}"
        run: |
          composer install
          npm install
          npm run prod
          vendor/bin/jigsaw build ${{ vars.JIGSAW_ENV || 'local' }}

      - name: Set Build Directory
        id: set_build_directory
        run: echo "build_directory=./build_${{ vars.JIGSAW_ENV || 'local' }}" >> $GITHUB_OUTPUT

      - name: Sync with S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          echo "############### REMOVE OLD SITE ###############"
          aws s3 rm s3://${{ secrets.S3_BUCKET }}/ --only-show-errors --recursive --region ${{ secrets.S3_REGION }}
          echo "############### COPY ##########################"
          aws s3 cp ${{ steps.set_build_directory.outputs.build_directory }} s3://${{ secrets.S3_BUCKET }} --only-show-errors --recursive --acl public-read --region ${{ secrets.S3_REGION }}

      - name: Invalidate Cloudfront Cache
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          echo "############### CACHE INVALIDATION ##############"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths="/*" --region ${{ secrets.S3_REGION }}
